services:
  - type: web
    name: AgroLink2
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true