services:
  - type: web
    name: agrolink2
    env: node
    plan: free
    buildCommand: |
      rm -rf node_modules
      npm install --production=false
      npm run build:server
      npm run build:frontend
    startCommand: node dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true